### ISSUE TITLE
Mistake in solution for 1_wanna_b3_a_r0ck5tar

### ISSUE THREAD

**Issue by StatsRhian** [Dvd848/CTFs#9] opened 2020-11-27 16:16 UTC
I think there is an issue in your solution for [1_wanna_b3_a_r0ck5tar](https://github.com/Dvd848/CTFs/blob/master/2019_picoCTF/1_wanna_b3_a_r0ck5tar.md)

In the Poetic Number Literals for Rockstar, a hyphen `-` is counted as another letter. 
Therefore `a six-string` should be `1 10(mod10) = 10` rather than `136`

Testing with 
```
A guitar is a six-string        
Say A guitar
```

on [Rockstar Online](https://codewithrockstar.com/online) demonstrates this.

Similarly - `a billboard-burning razzmatazz` should be `170` rather than `1970`

Thanks for posting your workings - really helped me understand Rockstar better!

**Comment by Dvd848** [comment] 2020-11-27 16:41
Duplicate of #8.

I think they changed the language specs at some stage - see the explanation in the duplicate issue. Maybe I should update the writeup with a clarification. 

Glad to hear that the writeups are helpful, thanks!

**Comment by Dvd848** [comment] 2020-11-30 17:21
Added a clarification, thanks again!

**Closed by Dvd848** 2020-11-30 17:21 UTC
